// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWDataExtractor.Data;

#nullable disable

namespace SWDataExtractor.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702062238_CimientosIniciales")]
    partial class CimientosIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SWDataExtractor.Data.Entities.AjusteApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ajustes_app", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT")
                        .HasColumnName("autor");

                    b.Property<string>("DatosExtraJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("datos_extra_json");

                    b.Property<string>("EstadoProfundo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado_profundo");

                    b.Property<string>("EstadoRapido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado_rapido");

                    b.Property<string>("FechaExtrProfunda")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_extr_profunda");

                    b.Property<string>("FechaExtrRapida")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_extr_rapida");

                    b.Property<string>("FechaModDisco")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_mod_disco");

                    b.Property<string>("HashSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("MensajeError")
                        .HasColumnType("TEXT")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("sistema_archivos")
                        .HasColumnName("origen");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ruta");

                    b.Property<string>("RutaPreview")
                        .HasColumnType("TEXT")
                        .HasColumnName("ruta_preview");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<int?>("VersionSw")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_sw");

                    b.HasKey("Id");

                    b.HasIndex("EstadoProfundo");

                    b.HasIndex("EstadoRapido");

                    b.HasIndex("HashSha256");

                    b.HasIndex("Ruta")
                        .IsUnique();

                    b.HasIndex("Tipo");

                    b.ToTable("archivos", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.ArchivoEtiqueta", b =>
                {
                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("etiqueta_id");

                    b.HasKey("ArchivoId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("archivo_etiquetas", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int?>("ComponenteArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("componente_archivo_id");

                    b.Property<string>("ConfiguracionUsada")
                        .HasColumnType("TEXT")
                        .HasColumnName("configuracion_usada");

                    b.Property<string>("DatosExtraJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("datos_extra_json");

                    b.Property<int>("EnsambleArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ensamble_archivo_id");

                    b.Property<int>("EnsambleConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ensamble_config_id");

                    b.Property<bool>("EsEnvelope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_envelope");

                    b.Property<bool>("EsToolbox")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_toolbox");

                    b.Property<string>("RutaReferenciada")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ruta_referenciada");

                    b.Property<bool>("Suprimido")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suprimido");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteArchivoId");

                    b.HasIndex("EnsambleArchivoId");

                    b.HasIndex("EnsambleConfigId");

                    b.HasIndex("EnsambleArchivoId", "EnsambleConfigId", "RutaReferenciada", "ConfiguracionUsada", "Suprimido")
                        .IsUnique();

                    b.ToTable("componentes", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_activa");

                    b.Property<bool>("EsDerivada")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_derivada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId", "Nombre")
                        .IsUnique();

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.DiccionarioPropiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nivel")
                        .HasColumnType("TEXT")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("obligatoria");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("ValoresPermitidosJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("valores_permitidos_json");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("diccionario_propiedades", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orden");

                    b.Property<string>("ParametrosJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("parametros_json");

                    b.Property<bool>("Suprimido")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suprimido");

                    b.Property<string>("TipoSw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_sw");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("Categoria");

                    b.HasIndex("TipoSw");

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.HistorialPropiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<string>("Configuracion")
                        .HasColumnType("TEXT")
                        .HasColumnName("configuracion");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lote_id");

                    b.Property<string>("Propiedad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("propiedad");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resultado");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("LoteId");

                    b.ToTable("historial_propiedades", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<int?>("ConfiguracionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("configuracion_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.Property<string>("ValorResuelto")
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_resuelto");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("Nombre");

                    b.HasIndex("ArchivoId", "ConfiguracionId", "Nombre")
                        .IsUnique();

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.PropiedadFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<double?>("AreaM2")
                        .HasColumnType("REAL")
                        .HasColumnName("area_m2");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("configuracion_id");

                    b.Property<double?>("DensidadKgM3")
                        .HasColumnType("REAL")
                        .HasColumnName("densidad_kg_m3");

                    b.Property<double?>("MasaKg")
                        .HasColumnType("REAL")
                        .HasColumnName("masa_kg");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<double?>("VolumenM3")
                        .HasColumnType("REAL")
                        .HasColumnName("volumen_m3");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("ArchivoId", "ConfiguracionId")
                        .IsUnique();

                    b.ToTable("propiedades_fisicas", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Rosca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<string>("Designacion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("designacion");

                    b.Property<double?>("DiametroNominalMm")
                        .HasColumnType("REAL")
                        .HasColumnName("diametro_nominal_mm");

                    b.Property<string>("Estandar")
                        .HasColumnType("TEXT")
                        .HasColumnName("estandar");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feature_id");

                    b.Property<double?>("HilosPorPulgada")
                        .HasColumnType("REAL")
                        .HasColumnName("hilos_por_pulgada");

                    b.Property<bool>("Pasante")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pasante");

                    b.Property<double?>("PasoMm")
                        .HasColumnType("REAL")
                        .HasColumnName("paso_mm");

                    b.Property<double?>("ProfundidadBarrenoMm")
                        .HasColumnType("REAL")
                        .HasColumnName("profundidad_barreno_mm");

                    b.Property<double?>("ProfundidadRoscaMm")
                        .HasColumnType("REAL")
                        .HasColumnName("profundidad_rosca_mm");

                    b.Property<string>("TipoBarreno")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_barreno");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("Designacion");

                    b.HasIndex("FeatureId");

                    b.ToTable("roscas", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.TrabajoExtraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchivoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archivo_id");

                    b.Property<long?>("DuracionMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duracion_ms");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("FechaEncolado")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_encolado");

                    b.Property<string>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos");

                    b.Property<string>("Mensaje")
                        .HasColumnType("TEXT")
                        .HasColumnName("mensaje");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("Estado", "Tipo");

                    b.ToTable("trabajos_extraccion", (string)null);
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.ArchivoEtiqueta", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("ArchivoEtiquetas")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWDataExtractor.Data.Entities.Etiqueta", "Etiqueta")
                        .WithMany("ArchivoEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Componente", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "ComponenteArchivo")
                        .WithMany("ComponentesComoComponente")
                        .HasForeignKey("ComponenteArchivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "EnsambleArchivo")
                        .WithMany("ComponentesComoEnsamble")
                        .HasForeignKey("EnsambleArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWDataExtractor.Data.Entities.Configuracion", "EnsambleConfig")
                        .WithMany("ComponentesComoEnsamble")
                        .HasForeignKey("EnsambleConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ComponenteArchivo");

                    b.Navigation("EnsambleArchivo");

                    b.Navigation("EnsambleConfig");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Configuracion", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("Configuraciones")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Feature", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("Features")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.HistorialPropiedad", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("HistorialPropiedades")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Propiedad", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("Propiedades")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWDataExtractor.Data.Entities.Configuracion", "Configuracion")
                        .WithMany("Propiedades")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Archivo");

                    b.Navigation("Configuracion");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.PropiedadFisica", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("PropiedadesFisicas")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWDataExtractor.Data.Entities.Configuracion", "Configuracion")
                        .WithMany("PropiedadesFisicas")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("Configuracion");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Rosca", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany()
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWDataExtractor.Data.Entities.Feature", "Feature")
                        .WithMany("Roscas")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.TrabajoExtraccion", b =>
                {
                    b.HasOne("SWDataExtractor.Data.Entities.Archivo", "Archivo")
                        .WithMany("TrabajosExtraccion")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Archivo", b =>
                {
                    b.Navigation("ArchivoEtiquetas");

                    b.Navigation("ComponentesComoComponente");

                    b.Navigation("ComponentesComoEnsamble");

                    b.Navigation("Configuraciones");

                    b.Navigation("Features");

                    b.Navigation("HistorialPropiedades");

                    b.Navigation("Propiedades");

                    b.Navigation("PropiedadesFisicas");

                    b.Navigation("TrabajosExtraccion");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Configuracion", b =>
                {
                    b.Navigation("ComponentesComoEnsamble");

                    b.Navigation("Propiedades");

                    b.Navigation("PropiedadesFisicas");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Etiqueta", b =>
                {
                    b.Navigation("ArchivoEtiquetas");
                });

            modelBuilder.Entity("SWDataExtractor.Data.Entities.Feature", b =>
                {
                    b.Navigation("Roscas");
                });
#pragma warning restore 612, 618
        }
    }
}
